apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - virtual-service.yaml
  - gateway.yaml
  - namespace.yaml
  - serviceentry-dev-get.yaml
  # MultiClusterService - adicionar manualmente quando necess√°rio
  # - multicluster-service.yaml