apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-engine
  namespace: mcs-demo
  labels:
    app: hello-app-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app-engine
  template:
    metadata:
      labels:
        app: hello-app-engine
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: hello-server
        image: nicolaka/netshoot:latest
        ports:
        - containerPort: 8080
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo '<html><body><h1>Hello from app-engine!</h1></body></html>' > /tmp/index.html
          python3 -m http.server 8080 --directory /tmp
