apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-master-engine
  namespace: mcs-demo
  labels:
    app: hello-master-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-master-engine
  template:
    metadata:
      labels:
        app: hello-master-engine
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: hello-server
        image: nicolaka/netshoot:latest
        ports:
        - containerPort: 8080
        command: ["/bin/sh"]
        args: ["-c", "echo '<html><body><h1>Hello from master-engine!</h1></body></html>' > /tmp/index.html && busybox httpd -f -p 8080 -h /tmp"]
