apiVersion: v1
kind: Service
metadata:
  name: hello-app-engine
  namespace: mcs-demo
  labels:
    app: hello-app-engine
spec:
  type: ClusterIP
  selector:
    app: hello-app-engine
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
